### ISSUE TITLE
Bug: Characters not named in the list

### ISSUE THREAD

**Issue by Solitus21** [BitsOfAByte/Wholist#2]
### Preflight Checklist

- [X] I have searched for existing issues and cannot find mine, or existing issues do not fit my report.

### Bug Behavior

Hello. Thanks for developing the feature.
I don't know if this is a bug or not, but I would like to report one.
When using "Wholist", when opening the "Character UI" or "search UI" screen, characters with no name appear in the list.
("すっぴん士" is "NoJob"'s Japanese name).
See the image for details.

(I'm using Deepl's translation, sorry if the English is weird.)

![image](https://user-images.githubusercontent.com/121738667/210159002-938462f1-09e7-4705-9147-58df79575095.png)
![image](https://user-images.githubusercontent.com/121738667/210159003-31b99e04-89f5-421a-8f42-e81b1098bcec.png)

### Expected Behavior

Is it desirable to remove unwanted information from the list?

**Comment by BitsOfAByte** [comment]
This will be fixed in the next release. It's due to the fact that when you open an examine window or adventurer plate, the game creates a new character at lvl0 in the interface. 

Thank you for reporting this!

**Comment by BitsOfAByte** [comment]
Fixed in 33316e7b8e9e30ef1475469a56401f75c1313783 and will be apart of the next release.
