### ISSUE TITLE
Feature: Sorting Options

### ISSUE THREAD

**Issue by KhaozFrost** [BitsOfAByte/Wholist#26]
### Preflight Checklist

- [X] I have searched for existing issues and cannot find mine, or existing issues do not fit.

### New or Existing?

New feature

### Summary of the feature

Firstly Alphabetical Sorting and then maybe some options to show the following in such order
- Party Members
- Friends
- FC Members
- Everyone Else

### Why should this be added or changed?

the code seems to be there based on how it shows color changes so thought maybe this could be added too.

**Comment by BitsOfAByte** [comment]
Implemented in d927b21ea31bd3ea0825bf4d89dc1d26c076b1d1. The list sorted alphabetically by default, and a configuration option to move “known players” (i.e. party members & friends) to the top of the list has been added.
