### ISSUE TITLE
Feature: show individual colors for jobs

### ISSUE THREAD

**Issue by tycho-bear** [BitsOfAByte/Wholist#32]
### Preflight Checklist

- [X] I have searched for existing issues and cannot find mine, or existing issues do not fit.

### New or Existing?

Improvement to existing feature

### Summary of the feature

At the moment, the "Role Colours" section displays jobs in red, green, or blue, based on whether the role is DPS, healer, or tank, respectively. It would be cool if we could also assign different colors to each individual job, much like FF Logs does [here](https://www.fflogs.com/zone/statistics/38#class=Any).

Perhaps this could also be disabled or enabled by a toggle, for those who prefer the simpler red/green/blue colors.

### Why should this be added or changed?

It would make it easier to distinguish between jobs at a glance in the `/who` window.

**Comment by BitsOfAByte** [comment]
Implemented in fdaa6fd6fc13592f98bea46ef21203e6e6b2a2d1
